apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hubot
  name: hubot
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hubot
    spec:
      containers:
      - args:
        - bash
        - -c
        - env HUBOT_SLACK_TOKEN=$HUBOT_SLACK_TOKEN bin/hubot -a slack
        env:
        - name: PORT
          value: "8000"
        - name: HUBOT_LOG_LEVEL
          value: debug
        - name: HUBOT_SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-token
              key: token
        - name: PAPERTRAIL_API_TOKEN
          value: bbCYxcSTm0BMdLchf3
        - name: REDIS_URL
          value: redis://redis-master:6379
        image: cfcontainersdp.azurecr.io/clearbot/hubot:da9024
        name: hubot
        ports:
        - containerPort: 8000
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hubot
  name: hubot
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: 8000
  selector:
    io.kompose.service: hubot
